services:
  - type: worker
    name: private-info-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: HENRIK_API_KEY
        sync: false
      - key: IS_WORKER
        value: "true" 