services:
  - type: web
    name: private-info-bot
    env: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: HENRIK_API_KEY
        sync: false
      - key: PORT
        value: "10000"
      - key: IS_RENDER
        value: "true" 